window.EnsignIntelStrings = {
  en: {
    dir: "ltr",
    lang: "en",
    cta: "Test Ensign Intelligence",
    overlay: {
      mark: "Ensign Intelligence",
      close: "Close",
    },
    unlock: {
      eyebrow: "STRATEGIC PREVIEW SESSION",
      headline: "Access Ensign Intelligence",
      sub: "Begin a limited strategic session built to analyse your business, identify growth gaps, and reveal where intelligence can create leverage.",
      name: "Name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@company.com",
      company: "Company or Project Name",
      companyPlaceholder: "Company name",
      industry: "Industry",
      industryPlaceholder: "Select your industry",
      industries: [
        "Real Estate",
        "Hospitality",
        "Luxury",
        "Events & Entertainment",
        "Government / Corporate",
        "Retail & E-commerce",
        "Technology",
        "Finance",
        "Healthcare",
        "Education",
        "Other",
      ],
      website: "Website URL (optional)",
      websitePlaceholder: "https://...",
      consent: "By starting this session, you agree that Ensign may use your submitted details and session insights to follow up with relevant services.",
      submit: "Begin Intelligence Session",
      note: "Each visitor receives one strategic preview session.",
      errorGeneric: "Something went wrong. Please try again.",
      errorFields: "Please complete all required fields with valid information.",
      errorEmail: "Please use a valid email address.",
    },
    loader: {
      line1: "Reading business context",
      line2: "Mapping operational signals",
      line3: "Preparing intelligence session",
    },
    chat: {
      fromAI: "Ensign Intelligence",
      fromUser: "You",
      placeholder: "Describe your challenge here…",
      send: "Send",
      turn: "TURN",
      of: "OF",
      synthesizing: "Synthesizing review",
    },
    hero: {
      headlinePrimary: "How can Ensign solve the challenge you’re facing today?",
      headlinePrimaryAccentWord: "Ensign",
      headlineSecondary: "استعرض، كيف يمكن لإنساين حل مشكلاتك بالذكاء الاصطناعي",
      headlineSecondaryAccentWord: "إنساين",
      sub: "Describe the challenge you are facing now, and let Ensign Intelligence analyse it through growth, operations, marketing, and systems.",
      intelligenceLabel: "PICK YOUR INTELLIGENCE",
      intelligenceSub: "Choose the intelligence layer most connected to the challenge you're facing today.",
      intelligences: [
        { id: "sales", title: "AI Sales Intelligence", desc: "Lead qualification, follow-up flow, conversion visibility, and sales momentum.", placeholder: "Describe the sales or conversion challenge…", opening: "I can help you uncover where leads are losing momentum, what slows conversion, and where the sales process may be leaking opportunities.\n\nWhat part of the sales flow feels weakest right now?" },
        { id: "marketing", title: "AI Marketing Intelligence", desc: "Campaign analysis, growth bottlenecks, audience behavior, and performance direction.", placeholder: "Describe the marketing or growth challenge…", opening: "I can help you identify what is slowing marketing performance, where campaign momentum is breaking, and what the numbers may not be revealing clearly yet.\n\nWhat feels like the biggest marketing issue right now?" },
        { id: "workflow", title: "Workflow Automation", desc: "Operational coordination, repetitive tasks, approvals, reminders, and process flow.", placeholder: "Describe the workflow or operational delay…", opening: "I can help you spot repetitive work, coordination delays, and the small operational bottlenecks that quietly slow teams down over time.\n\nWhat part of the workflow feels heavier than it should?" },
        { id: "reporting", title: "Reporting & Decision Intelligence", desc: "Operational visibility, reporting clarity, business insights, and executive decision support.", placeholder: "Describe the visibility or decision-making challenge…", opening: "I can help you find what leadership cannot see clearly yet, from weak reporting signals to missing performance visibility.\n\nWhat decision or business area currently feels unclear?" },
        { id: "content", title: "AI Content & Creative Systems", desc: "Content direction, messaging consistency, campaign thinking, and creative support.", placeholder: "Describe the content or creative challenge…", opening: "I can help you improve campaign messaging, content direction, creative consistency, and the ideas behind what your audience sees.\n\nWhat content or creative challenge are you trying to solve?" },
        { id: "agents", title: "AI Agents", desc: "Role-specific operational agents for sales, marketing, research, content, and internal coordination.", placeholder: "Describe the role or process you want intelligence to support…", opening: "I can help you identify which role-specific agents could support your team, reduce manual work, and improve how information moves across the company.\n\nWhat role or process do you wish had intelligent support inside your business?" },
      ],
    },
    modules: {
      heading: "SESSION SIGNAL",
      business_context: "Business Context",
      growth_signal: "Growth Signal",
      intelligence_depth: "Intelligence Depth",
      recommended_direction: "Recommended Direction",
      placeholders: {
        business_context: "Awaiting signal",
        growth_signal: "Not yet detected",
        intelligence_depth: "Initializing",
        recommended_direction: "Awaiting analysis",
      },
    },
    review: {
      eyebrow: "INITIAL REVIEW",
      title: "Initial Ensign Intelligence Review",
      closing: "Further analysis requires a direct Ensign engagement.",
      ctaBook: "Book a Strategy Call",
      ctaArch: "Request Full Architecture",
      sections: {
        business_signal: "Business Signal Detected",
        bottleneck: "Likely Growth Bottleneck",
        ai_opportunity: "AI / System Opportunity",
        marketing_opportunity: "Marketing or Sales Opportunity",
        direction: "Recommended Ensign Direction",
      },
    },
    returning: {
      eyebrow: "WELCOME BACK",
      headline: "Your initial intelligence review has already been completed.",
      sub: "Deeper analysis or full architecture mapping continues with the Ensign team directly.",
      ctaBook: "Book a Strategy Call",
      ctaArch: "Request Full Architecture",
      ctaContact: "Speak With Ensign",
    },
  },
  ar: {
    dir: "rtl",
    lang: "ar",
    cta: "جرّب ذكاء إنساين",
    overlay: {
      mark: "ذكاء إنساين",
      close: "إغلاق",
    },
    unlock: {
      eyebrow: "جلسة معاينة استراتيجية",
      headline: "ادخل إلى ذكاء إنساين",
      sub: "ابدأ جلسة استراتيجية محدودة تحلل نشاطك، تكشف فجوات النمو، وتوضح أين يمكن للذكاء أن يصنع فرقًا حقيقيًا.",
      name: "الاسم",
      namePlaceholder: "اسمك الكامل",
      email: "البريد الإلكتروني",
      emailPlaceholder: "you@company.com",
      company: "اسم الشركة أو المشروع",
      companyPlaceholder: "اسم الشركة",
      industry: "القطاع",
      industryPlaceholder: "اختر القطاع",
      industries: [
        "عقارات",
        "ضيافة",
        "فاخر",
        "فعاليات وترفيه",
        "حكومي / مؤسسي",
        "تجزئة وتجارة إلكترونية",
        "تقنية",
        "مالية",
        "صحة",
        "تعليم",
        "أخرى",
      ],
      website: "رابط الموقع الإلكتروني (اختياري)",
      websitePlaceholder: "https://...",
      consent: "ببدء هذه الجلسة، توافق على أن تستخدم إنساين بياناتك ومدخلات الجلسة للتواصل معك بخدمات ذات صلة.",
      submit: "ابدأ الجلسة الذكية",
      note: "لكل زائر جلسة استراتيجية واحدة.",
      errorGeneric: "حدث خطأ. حاول مرة أخرى.",
      errorFields: "يرجى إكمال جميع الحقول المطلوبة بمعلومات صحيحة.",
      errorEmail: "يرجى استخدام بريد إلكتروني صحيح.",
    },
    loader: {
      line1: "قراءة سياق النشاط",
      line2: "تحليل الإشارات التشغيلية",
      line3: "تجهيز الجلسة الذكية",
    },
    chat: {
      fromAI: "ذكاء إنساين",
      fromUser: "أنت",
      placeholder: "اكتب التحدي هنا…",
      send: "إرسال",
      turn: "الدور",
      of: "من",
      synthesizing: "تركيب المراجعة",
    },
    hero: {
      headlinePrimary: "استعرض، كيف يمكن لإنساين حل مشكلاتك بالذكاء الاصطناعي",
      headlinePrimaryAccentWord: "إنساين",
      headlineSecondary: "How can Ensign solve the challenge you’re facing today?",
      headlineSecondaryAccentWord: "Ensign",
      sub: "اكتب التحدي الذي تواجهه الآن، ودع ذكاء إنساين يبدأ بتحليله من منظور النمو، التشغيل، التسويق، والأنظمة.",
      intelligenceLabel: "اختر ذكاءك",
      intelligenceSub: "اختر طبقة الذكاء الأقرب للتحدي الذي تواجهه اليوم.",
      intelligences: [
        { id: "sales", title: "ذكاء المبيعات", desc: "تأهيل العملاء، تدفق المتابعة، وضوح التحويل، وزخم المبيعات.", placeholder: "اكتب تحدي المبيعات أو التحويل…", opening: "يمكنني مساعدتك في كشف أين يفقد العملاء المحتملون زخمهم، وما الذي يبطئ التحويل، وأين قد تتسرب الفرص من عملية المبيعات.\n\nأي جزء من تدفق المبيعات يبدو الأضعف الآن؟" },
        { id: "marketing", title: "ذكاء التسويق", desc: "تحليل الحملات، عوائق النمو، سلوك الجمهور، واتجاه الأداء.", placeholder: "اكتب تحدي التسويق أو النمو…", opening: "يمكنني مساعدتك في تحديد ما يبطئ أداء التسويق، وأين ينكسر زخم الحملات، وما الذي قد لا تكشفه الأرقام بوضوح بعد.\n\nما الذي يبدو أكبر مشكلة تسويقية الآن؟" },
        { id: "workflow", title: "أتمتة سير العمل", desc: "التنسيق التشغيلي، المهام المتكررة، الموافقات، التذكيرات، وتدفق العمليات.", placeholder: "اكتب تحدي سير العمل أو التأخير التشغيلي…", opening: "يمكنني مساعدتك في رصد العمل المتكرر، وتأخيرات التنسيق، والاختناقات التشغيلية الصغيرة التي تبطئ الفرق بهدوء مع الوقت.\n\nأي جزء من سير العمل يبدو أثقل مما ينبغي؟" },
        { id: "reporting", title: "ذكاء التقارير والقرار", desc: "الرؤية التشغيلية، وضوح التقارير، رؤى الأعمال، ودعم القرار التنفيذي.", placeholder: "اكتب تحدي الرؤية أو اتخاذ القرار…", opening: "يمكنني مساعدتك في إيجاد ما لا تستطيع القيادة رؤيته بوضوح بعد، من إشارات التقارير الضعيفة إلى الرؤية المفقودة للأداء.\n\nأي قرار أو مجال في العمل يبدو غير واضح حالياً؟" },
        { id: "content", title: "أنظمة المحتوى والإبداع", desc: "اتجاه المحتوى، اتساق الرسائل، التفكير الحملي، ودعم الإبداع.", placeholder: "اكتب تحدي المحتوى أو الإبداع…", opening: "يمكنني مساعدتك في تحسين رسائل الحملات، اتجاه المحتوى، اتساق الإبداع، والأفكار خلف ما يراه جمهورك.\n\nما تحدي المحتوى أو الإبداع الذي تحاول حلّه؟" },
        { id: "agents", title: "وكلاء الذكاء", desc: "وكلاء تشغيليون متخصصون للمبيعات، التسويق، البحث، المحتوى، والتنسيق الداخلي.", placeholder: "اكتب الدور أو العملية التي تريد دعم الذكاء فيها…", opening: "يمكنني مساعدتك في تحديد أي الوكلاء المتخصصين قد يدعمون فريقك، يقلّلون العمل اليدوي، ويحسّنون كيف تنتقل المعلومات داخل الشركة.\n\nأي دور أو عملية تتمنى لو كان لديها دعم ذكي داخل أعمالك؟" },
      ],
    },
    modules: {
      heading: "إشارة الجلسة",
      business_context: "سياق الأعمال",
      growth_signal: "إشارة النمو",
      intelligence_depth: "عمق التحليل",
      recommended_direction: "الاتجاه المقترح",
      placeholders: {
        business_context: "في انتظار الإشارة",
        growth_signal: "لم يتم اكتشافها بعد",
        intelligence_depth: "جاري التهيئة",
        recommended_direction: "في انتظار التحليل",
      },
    },
    review: {
      eyebrow: "المراجعة الأولية",
      title: "المراجعة الأولية من ذكاء إنساين",
      closing: "يتطلب التحليل الأعمق تواصلًا مباشرًا مع إنساين.",
      ctaBook: "احجز جلسة استراتيجية",
      ctaArch: "اطلب التصور الكامل",
      sections: {
        business_signal: "الإشارة التجارية المكتشفة",
        bottleneck: "العائق الأرجح للنمو",
        ai_opportunity: "فرصة الذكاء أو النظام",
        marketing_opportunity: "فرصة التسويق أو المبيعات",
        direction: "التوجه المقترح من إنساين",
      },
    },
    returning: {
      eyebrow: "أهلًا بعودتك",
      headline: "تم إكمال مراجعتك الذكية الأولية.",
      sub: "للحصول على تحليل أعمق أو بناء تصور كامل للنظام، يمكنك الانتقال إلى الخطوة التالية مع إنساين.",
      ctaBook: "احجز جلسة استراتيجية",
      ctaArch: "اطلب التصور الكامل",
      ctaContact: "تواصل مع إنساين",
    },
  },
};
